# Generated by Django 5.0.4 on 2024-05-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_num_ratings_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
