# Generated by Django 5.0.4 on 2024-05-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
