# Generated by Django 5.0.4 on 2024-06-09 20:27

from django.db import migrations, models

def populate_session_id(apps, schema_editor):
    Purchase = apps.get_model('books', 'Purchase')
    for purchase in Purchase.objects.all():
        purchase.session_id = 'default_session_id'  # Or generate a session ID
        purchase.save()

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_purchase_session_id'),
    ]

    operations = [
        migrations.RunPython(populate_session_id),
    ]
