# Generated by Django 5.0.4 on 2024-06-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20240609_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
