# Generated by Django 5.0.4 on 2024-06-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_purchase_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='session_id',
        ),
    ]
