# Generated by Django 5.0.4 on 2024-06-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/images/pfps/pfp.jpg', upload_to='images/pfps/'),
        ),
    ]
