# Generated by Django 5.0.4 on 2024-06-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copyright_notice',
            field=models.CharField(default='© Author Name. All rights reserved.', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='watermarked_file',
            field=models.FileField(blank=True, null=True, upload_to='watermarked_files/'),
        ),
    ]
